#!/usr/bin/python3
########################
# Written by HAHALOSAH #
########################
import requests
import json
f = open("token.txt", "r")
token = f.read()
f.close()
if selectedserver != "":
  baseURL = "https://discordapp.com/api/v8/users/@me/guilds/" + parama
  headers = { "Authorization": token, "User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36",
              "Content-Type":"application/json"}
  
  r = requests.delete(baseURL, headers = headers)
  #print(r.status_code)\
  if r.status_code == 204:
    print("Left the server")
    server = ""
  else:
    print("Error " + str(r.status_code) + ": " + r.text)
else:
  print("Select a server first! >>> select server <id>")

exec(open("servers.py").read())
exec(open("update-info.py").read())
