#!/usr/bin/python3
########################
# Written by HAHALOSAH #
########################
import requests
import json
if len(args) == 2:
  f = open("token.txt", "r")
  token = f.read()
  f.close()
  baseURL = "https://discordapp.com/api/v8/users/@me/relationships/" + parama
  headers = { "Authorization": token, "User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36",
              "Content-Type":"application/json"}
  r = requests.delete(baseURL, headers = headers)
  #print(r.status_code)\
  if r.status_code == 204:
    print("Unblocked the user")
  else:
    print("Error " + str(r.status_code) + ": " + r.text)
else:
  print("This command takes 2 arguments. " + str(len(args)) + " was supplied.")


